### ISSUE TITLE
Can you. please tell me HOW. TO COMPILE? ?

### ISSUE THREAD

**Issue by ihexon** [SUP3RD3AD/DDoS-Scripts#1]
Can you. please tell me HOW. TO COMPILE? ?
Or write a simple Makefile....
Thanks：)

**Comment by LOLSquad** [comment]
use GCC.
Example: gcc -o SSDP SSDP.c -pthread

**Comment by ihexon** [comment]
Oh, yes FLAGS "-pthread" 
 Thanks：)
